```yaml
pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    def sonarProperties = ['sonar.projectKey=my-java-app',
                                            'sonar.sources=src/main/java',
                                            'sonar.test.inclusions=test/**/*.java']

                    def sonarRunnerCommand = "mvn -Dsonar.host.url=${sonarHost} -Dsonar.login=${sonarToken} \
                                              -Dsonar.projectVersion=$(git rev-parse --short HEAD) \
                                              -Dsonar.qualityGateBranchStatusEnabled=true \
                                              -Dsonar.projectName=my-java-app \
                                              -Dsonar.projectBaseDir=.\${WORKSPACE} \
                                              -Dmaven.test.failure.ignore=false ${sonarProperties.join(' ')}"
                    
                    sh sonarRunnerCommand
                }
            }
        }

        stage('Docker Build') {
            steps {
                script {
                    def dockerfilePath = "${WORKSPACE}/target/${env.JOB_NAME}-${env.BUILD_ID}.jar"
                    sh "mvn -f ${dockerfileProject} clean package --file pom.xml -DskipTests=true -DskipITs=true"
                    sh "cp target/*.jar ${dockerfilePath}"
                    sh 'mkdir -p docker'
                    sh "cp ${WORKSPACE}/target/${env.JOB_NAME}-${env.BUILD_ID}.jar docker/"
                    sh 'docker build -t my-java-app:latest .'
                }
            }
        }

        stage('Docker Push') {
            steps {
                script {
                    env.DOCKER_PASSWORD = "${dockerPassword}"
                    sh "echo ${DOCKER_PASSWORD} | docker login -u ${dockerUsername} --password-stdin"
                    sh "docker push my-java-app:latest"
                }
            }
        }

        stage('Kubernetes Deployment') {
            steps {
                script {
                    def k8sManifestPath = "${WORKSPACE}/deploy/kustomize/my-java-app.yaml"

                    sh "kubectl apply -k ${k8sManifestPath}"
                }
            }
        }
    }
}
```